"""type of time_created in Post changed from Datetime to String

Revision ID: 6d452b83a7d6
Revises: ed69a5ed470c
Create Date: 2022-01-31 18:29:51.616363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d452b83a7d6'
down_revision = 'ed69a5ed470c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
