"""sender&receiver

Revision ID: 9352ee05af5e
Revises: b3f1f6cf37f9
Create Date: 2021-12-19 15:34:09.312645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9352ee05af5e'
down_revision = 'b3f1f6cf37f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("messages_users_receiver_fk", 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key("messages_users_sender_fk", 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
