"""Init revision

Revision ID: b3f1f6cf37f9
Revises: 
Create Date: 2021-12-18 22:13:15.495337

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3f1f6cf37f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('time_send', sa.DateTime(), nullable=True),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('is_important', sa.Boolean(), nullable=True),
                    sa.Column('is_edited', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('surname', sa.String(), nullable=True),
                    sa.Column('photo', sa.String(), nullable=True),
                    sa.Column('additional_data', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    # ### end Alembic commands ###
