"""Relationship between dialog and message

Revision ID: edfa16fe34fa
Revises: 4c429739d7ba
Create Date: 2022-01-22 17:06:37.646483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfa16fe34fa'
down_revision = '4c429739d7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialog_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('messages_users_receiver_fk', type_='foreignkey')
        batch_op.create_foreign_key("dialogs_messages_fk", 'dialogs', ['dialog_id'], ['id'])
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_users_receiver_fk', 'users', ['receiver_id'], ['id'])
        batch_op.drop_column('dialog_id')

    # ### end Alembic commands ###
